--说明 开发环境对数据库进行修改操作,对表执行变动的sql添加,顺序倒序,格式如下
--日期:2019-01-08 11:00:00
--alter table t_sdryxx add  txxx varchar2(32);
--COMMENT ON COLUMN "MAILDATA"."T_SDRYXX"."TXXX" IS '通讯信息';

---------------------该分割线下新增sql语句----------------------------------------
----执行过的sql请勿再执行

--2019年1月16日15:42:14

----------------------------------------------------------------------字典----------------------------------------------------------------------

CREATE TABLE P_DICTION_11
(
  ID NUMBER NOT NULL
, PID NUMBER
, DLEVEL NUMBER
, KEYS VARCHAR2(32 BYTE)
, VAL VARCHAR2(32 BYTE)
, DESCS VARCHAR2(255 BYTE)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT P_DICTION_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 8192
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

ALTER TABLE P_DICTION_11
ADD CONSTRAINT SYS_C0063779 CHECK
(ID IS NOT NULL)
ENABLE;

COMMENT ON COLUMN P_DICTION_11_11.ID IS '编号';
COMMENT ON COLUMN P_DICTION_11.PID IS '父类编号';
COMMENT ON COLUMN P_DICTION_11.DLEVEL IS '0父类,1代表1级字典...';
COMMENT ON COLUMN P_DICTION_11.KEYS IS '对应编码值';
COMMENT ON COLUMN P_DICTION_11.VAL IS '对应中文描述';
COMMENT ON COLUMN P_DICTION_11.CREATEUID IS '创建人ID';
COMMENT ON COLUMN P_DICTION_11.CREATENAME IS '创建人姓名';
COMMENT ON COLUMN P_DICTION_11.LASTMODIFYUID IS '修改人';
COMMENT ON COLUMN P_DICTION_11.CREATETIME IS '创建时间';
COMMENT ON COLUMN P_DICTION_11.LASTMODIFYTIME IS '修改时间';
COMMENT ON COLUMN P_DICTION_11.DESCS IS '描述';

----------------------------------------------------------------------流程分配----------------------------------------------------------------------
CREATE TABLE F_FLOWALLOT_11
(
  ID NUMBER NOT NULL
, BUSI VARCHAR2(24 BYTE)
, BUSINAME VARCHAR2(48 CHAR)
, FLOWTYPE NUMBER
, DID NUMBER
, DEPNAME VARCHAR2(48 CHAR)
, PID NUMBER
, DUTYNAME VARCHAR2(48 CHAR)
, USERID NUMBER
, USERNAME VARCHAR2(48 CHAR)
, FLOWDEFID NUMBER
, FLOWNAME VARCHAR2(48 CHAR)
, CONDITION VARCHAR2(128 CHAR)
, RUNS NUMBER
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT F_FLOWALLOT_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

COMMENT ON COLUMN F_FLOWALLOT_11.BUSI IS '适用业务 flowType=9可不填';
COMMENT ON COLUMN F_FLOWALLOT_11.BUSINAME IS '使用业务名称 flowType=9可不填';
COMMENT ON COLUMN F_FLOWALLOT_11.FLOWTYPE IS '0指定人,1部门+角色, 2角色 9是默认';
COMMENT ON COLUMN F_FLOWALLOT_11.DID IS '部门编号';
COMMENT ON COLUMN F_FLOWALLOT_11.DEPNAME IS '部门名称';
COMMENT ON COLUMN F_FLOWALLOT_11.PID IS '职位编号';
COMMENT ON COLUMN F_FLOWALLOT_11.DUTYNAME IS '职位名称';
COMMENT ON COLUMN F_FLOWALLOT_11.USERID IS '指定人';
COMMENT ON COLUMN F_FLOWALLOT_11.USERNAME IS '用户名称';
COMMENT ON COLUMN F_FLOWALLOT_11.FLOWDEFID IS '对应流程id';
COMMENT ON COLUMN F_FLOWALLOT_11.FLOWNAME IS '流程名称';
COMMENT ON COLUMN F_FLOWALLOT_11.CONDITION IS '其它条件,非开发预设选项请勿填写';
COMMENT ON COLUMN F_FLOWALLOT_11.RUNS IS '是否启用';
COMMENT ON COLUMN F_FLOWALLOT_11.CREATEUID IS '创建人ID';
COMMENT ON COLUMN F_FLOWALLOT_11.LASTMODIFYUID IS '最近修改人ID';
COMMENT ON COLUMN F_FLOWALLOT_11.CREATETIME IS '创建时间';
COMMENT ON COLUMN F_FLOWALLOT_11.LASTMODIFYTIME IS '最近修改时间';



----------------------------------------------------------------------流程定义----------------------------------------------------------------------
CREATE TABLE F_FLOWDEF_11
(
  ID NUMBER NOT NULL
, FNAME VARCHAR2(64 BYTE)
, FDESC VARCHAR2(64 BYTE)
, REMARK VARCHAR2(64 BYTE)
, INSDEFID NUMBER
, FLEVEL NUMBER(2, 0)
, PARENTID NUMBER
, INITMODE NUMBER(2, 0)
, INITUSE NUMBER(2, 0)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT FLOWDEF_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 8192
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

ALTER TABLE F_FLOWDEF_11
ADD CONSTRAINT SYS_C0050120 CHECK
(ID IS NOT NULL)
ENABLE;

COMMENT ON COLUMN F_FLOWDEF_11.FNAME IS '流程名称';
COMMENT ON COLUMN F_FLOWDEF_11.FDESC IS '流程描述';
COMMENT ON COLUMN F_FLOWDEF_11.REMARK IS '备注';
COMMENT ON COLUMN F_FLOWDEF_11.INSDEFID IS '流程副本ID,当修改COPYID会清空';
COMMENT ON COLUMN F_FLOWDEF_11.CREATETIME IS '创建时间';
COMMENT ON COLUMN F_FLOWDEF_11.LASTMODIFYTIME IS '操作时间,新增和修改时候会更新';
COMMENT ON COLUMN F_FLOWDEF_11.FLEVEL IS '级别,0为父类作为分配使用,1为副本作为流程实用';
COMMENT ON COLUMN F_FLOWDEF_11.CREATEUID IS '创建用户';
COMMENT ON COLUMN F_FLOWDEF_11.LASTMODIFYUID IS '操作用户';
COMMENT ON COLUMN F_FLOWDEF_11.PARENTID IS '父类ID';
COMMENT ON COLUMN F_FLOWDEF_11.INITMODE IS '启禁状态，禁用时候，对外接口不显示';
COMMENT ON COLUMN F_FLOWDEF_11.INITUSE IS '是否默认，有且只有一个，默认时候不可删除，不可禁用';

----------------------------------------------------------------------流程实体----------------------------------------------------------------------
CREATE TABLE F_FLOWINS_11
(
  ID VARCHAR2(20 BYTE) NOT NULL
, BUSIID VARCHAR2(32 BYTE)
, FDID NUMBER
, FNID NUMBER
, UIDS VARCHAR2(480 BYTE)
, HOSTID NUMBER
, STATUS NUMBER(2, 0)
, STATUSSTR VARCHAR2(32 BYTE)
, CURSPUIDS VARCHAR2(512 BYTE)
, SYSID VARCHAR2(128 BYTE)
, SYSNAME VARCHAR2(128 BYTE)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT FLOWINS_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 8192
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

ALTER TABLE F_FLOWINS_11
ADD CONSTRAINT SYS_C0050124 CHECK
(ID IS NOT NULL)
ENABLE;

COMMENT ON COLUMN F_FLOWINS_11.BUSIID IS '业务数据ID';
COMMENT ON COLUMN F_FLOWINS_11.FDID IS '流程对象ID';
COMMENT ON COLUMN F_FLOWINS_11.FNID IS '流程节点ID';
COMMENT ON COLUMN F_FLOWINS_11.UIDS IS '指定人审批人';
COMMENT ON COLUMN F_FLOWINS_11.HOSTID IS '待办人';
COMMENT ON COLUMN F_FLOWINS_11.STATUS IS '流程状态0保存,1驳回,2提交,3审批中,99通过,-1拒绝';
COMMENT ON COLUMN F_FLOWINS_11.STATUSSTR IS '状态描述';
COMMENT ON COLUMN F_FLOWINS_11.CURSPUIDS IS '当前审批人员';
COMMENT ON COLUMN F_FLOWINS_11.SYSID IS '应用系统id';
COMMENT ON COLUMN F_FLOWINS_11.SYSNAME IS '应用系统名称';


----------------------------------------------------------------------流程节点----------------------------------------------------------------------
CREATE TABLE F_FLOWNODE_11
(
  ID VARCHAR2(20 BYTE) NOT NULL
, FDID NUMBER
, NNAME VARCHAR2(32 BYTE)
, NBNAME VARCHAR2(32 BYTE)
, NANAME VARCHAR2(32 BYTE)
, SPTYPE NUMBER(2, 0)
, DEPID NUMBER
, ROLEIDS VARCHAR2(128 BYTE)
, USERIDS VARCHAR2(128 BYTE)
, USERBACK NUMBER(2, 0)
, SPBACK NUMBER(2, 0)
, BACKDOT NUMBER(2, 0)
, ORDERS NUMBER
, GOEND NUMBER(2, 0)
, REJECT NUMBER(2, 0)
, SYSID VARCHAR2(255 BYTE)
, CURSPUIDS VARCHAR2(255 BYTE)
, SYSNAME VARCHAR2(255 BYTE)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT FLOWNODE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 8192
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

ALTER TABLE F_FLOWNODE_11
ADD CONSTRAINT SYS_C0050122 CHECK
(ID IS NOT NULL)
ENABLE;

COMMENT ON COLUMN F_FLOWNODE_11.FDID IS '流程对象ID';
COMMENT ON COLUMN F_FLOWNODE_11.NNAME IS '节点名称';
COMMENT ON COLUMN F_FLOWNODE_11.NBNAME IS '触发描述';
COMMENT ON COLUMN F_FLOWNODE_11.NANAME IS '审批后名称';
COMMENT ON COLUMN F_FLOWNODE_11.SPTYPE IS '0指定人 -1指定部门+角色 1本部门+角色 2上级部门+角色 3/4/5...依次往上部门+角色 99最高部门+角色';
COMMENT ON COLUMN F_FLOWNODE_11.DEPID IS '本部门/指定部门';
COMMENT ON COLUMN F_FLOWNODE_11.ROLEIDS IS '指定角色';
COMMENT ON COLUMN F_FLOWNODE_11.USERIDS IS '指定审批人';
COMMENT ON COLUMN F_FLOWNODE_11.USERBACK IS '发起人是否可以撤回';
COMMENT ON COLUMN F_FLOWNODE_11.SPBACK IS '审批人是否可以撤回';
COMMENT ON COLUMN F_FLOWNODE_11.BACKDOT IS '驳回接受点';
COMMENT ON COLUMN F_FLOWNODE_11.ORDERS IS '流程顺序';
COMMENT ON COLUMN F_FLOWNODE_11.GOEND IS '直接通过';
COMMENT ON COLUMN F_FLOWNODE_11.REJECT IS '审批人驳回权限';

----------------------------------------------------------------------审批记录----------------------------------------------------------------------
CREATE TABLE F_SPINFO_11
(
  ID NUMBER NOT NULL
, INSID NUMBER
, SPTYPE NUMBER(2, 0)
, SPINFO VARCHAR2(500 BYTE)
, FNID NUMBER
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT SPINFO_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 8192
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

ALTER TABLE F_SPINFO_11
ADD CONSTRAINT SYS_C0050126 CHECK
(ID IS NOT NULL)
ENABLE;

COMMENT ON COLUMN F_SPINFO_11.INSID IS '流程实体ID';
COMMENT ON COLUMN F_SPINFO_11.SPTYPE IS '审批操作0保存 1驳回 2同意 3提交 4撤回 9通过 -1不同意';
COMMENT ON COLUMN F_SPINFO_11.SPINFO IS '审批意见';
COMMENT ON COLUMN F_SPINFO_11.FNID IS '审批当前节点';


----------------------------------------------------------------------日志----------------------------------------------------------------------
CREATE TABLE I_LOGSYS_11
(
  ID VARCHAR2(32 BYTE) NOT NULL
, ENTITYID VARCHAR2(32 CHAR)
, GOAL VARCHAR2(128 CHAR)
, LOGDATE TIMESTAMP(6)
, CASEID VARCHAR2(64 CHAR)
, CASENAME VARCHAR2(128 CHAR)
, OBJID VARCHAR2(64 CHAR)
, IP VARCHAR2(48 CHAR)
, ITEMTAG VARCHAR2(64 CHAR)
, ITEMNAME VARCHAR2(64 CHAR)
, DEPNAME VARCHAR2(64 CHAR)
, DEPID NUMBER
, RANGES CLOB
, OPERDESC CLOB
, SYSDESC CLOB
, LOGDESC CLOB
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT I_LOGSYS_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
LOB (RANGES) STORE AS SYS_LOB0000228050C00017$$
(
  ENABLE STORAGE IN ROW
  CHUNK 8192
  RETENTION
  NOCACHE
  LOGGING
  TABLESPACE "VILLAGE"
  STORAGE
  (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
)
LOB (OPERDESC) STORE AS SYS_LOB0000228050C00018$$
(
  ENABLE STORAGE IN ROW
  CHUNK 8192
  RETENTION
  NOCACHE
  LOGGING
  TABLESPACE "VILLAGE"
  STORAGE
  (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
)
LOB (SYSDESC) STORE AS SYS_LOB0000228050C00019$$
(
  ENABLE STORAGE IN ROW
  CHUNK 8192
  RETENTION
  NOCACHE
  LOGGING
  TABLESPACE "VILLAGE"
  STORAGE
  (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
)
LOB (LOGDESC) STORE AS SYS_LOB0000228050C00020$$
(
  ENABLE STORAGE IN ROW
  CHUNK 8192
  RETENTION
  NOCACHE
  LOGGING
  TABLESPACE "VILLAGE"
  STORAGE
  (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
);

COMMENT ON COLUMN I_LOGSYS_11.ENTITYID IS '对应实体类ID';
COMMENT ON COLUMN I_LOGSYS_11.GOAL IS '执法目标';
COMMENT ON COLUMN I_LOGSYS_11.LOGDATE IS '日志时间';
COMMENT ON COLUMN I_LOGSYS_11.CASEID IS '案件ID';
COMMENT ON COLUMN I_LOGSYS_11.CASENAME IS '案件名称';
COMMENT ON COLUMN I_LOGSYS_11.OBJID IS '对象ID';
COMMENT ON COLUMN I_LOGSYS_11.IP IS '访问IP';
COMMENT ON COLUMN I_LOGSYS_11.ITEMTAG IS '模块标识';
COMMENT ON COLUMN I_LOGSYS_11.ITEMNAME IS '模块名称';
COMMENT ON COLUMN I_LOGSYS_11.DEPID IS '部门ID';
COMMENT ON COLUMN I_LOGSYS_11.RANGES IS '查询条件 例如:用户=张三,时间2019-01-01至2019-01-10等';
COMMENT ON COLUMN I_LOGSYS_11.OPERDESC IS '操作描述例如:登陆,退出,定时任务,查询,新增修改,删除,发布等';
COMMENT ON COLUMN I_LOGSYS_11.SYSDESC IS '系统消息描述: xxx登陆,执行xx定时任务是否成功,等';
COMMENT ON COLUMN I_LOGSYS_11.LOGDESC IS '日志描述: 对保存改日志的书面描述,以用户理解为主等';
COMMENT ON COLUMN I_LOGSYS_11.DEPNAME IS '用户所属部门';


----------------------------------------------------------------------消息订阅----------------------------------------------------------------------

CREATE TABLE M_CUSTOM_11
(
  ID NUMBER NOT NULL
, USERID NUMBER
, TIPSCONF VARCHAR2(50 BYTE)
, SUBSCRIBE NUMBER
, REMIND NUMBER
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT M_CUSTOM_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

COMMENT ON COLUMN M_CUSTOM_11.USERID IS '订阅用户';
COMMENT ON COLUMN M_CUSTOM_11.TIPSCONF IS '消息类型';
COMMENT ON COLUMN M_CUSTOM_11.SUBSCRIBE IS '订阅';
COMMENT ON COLUMN M_CUSTOM_11.REMIND IS '提醒';

----------------------------------------------------------------------消息信息----------------------------------------------------------------------
CREATE TABLE M_MSG_11
(
  ID NUMBER NOT NULL
, RECEIVEUSERID NUMBER
, READ NUMBER
, TIPS VARCHAR2(50 BYTE)
, CONTENT VARCHAR2(500 BYTE)
, ENTITYID VARCHAR2(32 BYTE)
, CASEID VARCHAR2(50 BYTE)
, PARAM VARCHAR2(200 CHAR)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT M_MSG_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

COMMENT ON COLUMN M_MSG_11.RECEIVEUSERID IS '接收用户';
COMMENT ON COLUMN M_MSG_11.READ IS '是否已读';
COMMENT ON COLUMN M_MSG_11.TIPS IS '消息类型';
COMMENT ON COLUMN M_MSG_11.CONTENT IS '消息内容';
COMMENT ON COLUMN M_MSG_11.ENTITYID IS '业务ID';
COMMENT ON COLUMN M_MSG_11.CASEID IS '案件ID';
COMMENT ON COLUMN M_MSG_11.PARAM IS '额外参数';

----------------------------------------------------------------------提醒信息----------------------------------------------------------------------
CREATE TABLE M_TOUCH_11
(
  ID NUMBER NOT NULL
, RECEIVEUSERID NUMBER
, VALID TIMESTAMP(6)
, TIPS VARCHAR2(50 BYTE)
, MSGID NUMBER
, CONTENT VARCHAR2(500 BYTE)
, ENTITYID VARCHAR2(32 BYTE)
, DURATION NUMBER
, CASEID VARCHAR2(50 BYTE)
, PARAM VARCHAR2(200 CHAR)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT M_TOUCH_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

COMMENT ON COLUMN M_TOUCH_11.RECEIVEUSERID IS '接收人';
COMMENT ON COLUMN M_TOUCH_11.VALID IS '有效期';
COMMENT ON COLUMN M_TOUCH_11.TIPS IS '消息类型';
COMMENT ON COLUMN M_TOUCH_11.MSGID IS '对应订阅ID';
COMMENT ON COLUMN M_TOUCH_11.CONTENT IS '内容';
COMMENT ON COLUMN M_TOUCH_11.ENTITYID IS '业务实体';
COMMENT ON COLUMN M_TOUCH_11.DURATION IS '展示时长 秒';
COMMENT ON COLUMN M_TOUCH_11.CASEID IS '案件ID';
COMMENT ON COLUMN M_TOUCH_11.PARAM IS '额外参数';

----------------------------------------------------------------------聊天信息----------------------------------------------------------------------
CREATE TABLE M_TALK_11
(
  ID VARCHAR2(32 BYTE) NOT NULL
, RECEIVEUSERID NUMBER
, SENDUSERNAME VARCHAR2(50 CHAR)
, RECEIVEUSERNAME VARCHAR2(50 CHAR)
, CONTENT VARCHAR2(2000 BYTE)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT M_TALK_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

COMMENT ON COLUMN M_TALK_11.RECEIVEUSERID IS '接收人ID';
COMMENT ON COLUMN M_TALK_11.SENDUSERNAME IS '发送人姓名';
COMMENT ON COLUMN M_TALK_11.RECEIVEUSERNAME IS '接收人姓名';


----------------------------------------------------------------------公告----------------------------------------------------------------------
CREATE TABLE S_NOTE_11
(
  ID VARCHAR2(32 BYTE) NOT NULL
, NOTETITLE VARCHAR2(255 BYTE)
, AUTHOR VARCHAR2(30 BYTE)
, EXPERDAYS NUMBER
, CONTENT CLOB
, RELEASE NUMBER
, ROOF NUMBER
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT S_NOTE_11_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 8192
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
LOB (CONTENT) STORE AS SYS_LOB0000231086C00009$$
(
  ENABLE STORAGE IN ROW
  CHUNK 8192
  RETENTION
  NOCACHE
  LOGGING
  TABLESPACE "VILLAGE"
  STORAGE
  (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
);

COMMENT ON COLUMN S_NOTE_11.ID IS '主键id';
COMMENT ON COLUMN S_NOTE_11.NOTETITLE IS '通告标题';
COMMENT ON COLUMN S_NOTE_11.AUTHOR IS '发布人';
COMMENT ON COLUMN S_NOTE_11.EXPERDAYS IS '过期时间';
COMMENT ON COLUMN S_NOTE_11.CONTENT IS '公告内容';
COMMENT ON COLUMN S_NOTE_11.RELEASE IS '是否发布';
COMMENT ON COLUMN S_NOTE_11.ROOF IS '置顶';

----------------------------------------------------------------------部门----------------------------------------------------------------------
CREATE TABLE I_DEPART_11
(
  ID NUMBER NOT NULL
, DNAME VARCHAR2(100 BYTE)
, DDESC VARCHAR2(200 BYTE)
, DLEVEL NUMBER(2, 0)
, REMARK VARCHAR2(200 BYTE)
, PARENTID NUMBER(10, 0)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT DEPART_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

ALTER TABLE I_DEPART_11
ADD CONSTRAINT SYS_C0050116 CHECK
(ID IS NOT NULL)
ENABLE;

COMMENT ON COLUMN I_DEPART_11.ID IS '部门id';
COMMENT ON COLUMN I_DEPART_11.DNAME IS '部门名称';
COMMENT ON COLUMN I_DEPART_11.DDESC IS '部门描述';
COMMENT ON COLUMN I_DEPART_11.DLEVEL IS '部门级别';
COMMENT ON COLUMN I_DEPART_11.CREATETIME IS '创建时间';
COMMENT ON COLUMN I_DEPART_11.LASTMODIFYTIME IS '更新时间';
COMMENT ON COLUMN I_DEPART_11.CREATEUID IS '创建人id';
COMMENT ON COLUMN I_DEPART_11.LASTMODIFYUID IS '更新人id';
COMMENT ON COLUMN I_DEPART_11.REMARK IS '备注';
COMMENT ON COLUMN I_DEPART_11.DELFLAG IS '是否删除';
COMMENT ON COLUMN I_DEPART_11.PARENTID IS '父级部门';


----------------------------------------------------------------------职位----------------------------------------------------------------------
CREATE TABLE I_DUTY_11
(
  ID NUMBER NOT NULL
, DUTYNAME VARCHAR2(100 BYTE)
, DDESC VARCHAR2(200 BYTE)
, DLEVEL NUMBER(2, 0)
, REMARK VARCHAR2(100 BYTE)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT DUTY_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

ALTER TABLE I_DUTY_11
ADD CONSTRAINT SYS_C0050118 CHECK
(ID IS NOT NULL)
ENABLE;

COMMENT ON COLUMN I_DUTY_11.ID IS '职位id';
COMMENT ON COLUMN I_DUTY_11.DUTYNAME IS '职位名称';
COMMENT ON COLUMN I_DUTY_11.DDESC IS '职位描述';
COMMENT ON COLUMN I_DUTY_11.DLEVEL IS '职位级别';
COMMENT ON COLUMN I_DUTY_11.CREATETIME IS '创建时间';
COMMENT ON COLUMN I_DUTY_11.LASTMODIFYTIME IS '更新时间';
COMMENT ON COLUMN I_DUTY_11.CREATEUID IS '创建人id';
COMMENT ON COLUMN I_DUTY_11.LASTMODIFYUID IS '更新人id';
COMMENT ON COLUMN I_DUTY_11.DELFLAG IS '是否删除';

----------------------------------------------------------------------操作权限----------------------------------------------------------------------
CREATE TABLE S_OPERATE_11
(
  ID NUMBER NOT NULL
, OCODE VARCHAR2(64 BYTE)
, ONAME VARCHAR2(64 BYTE)
, TYPENAME VARCHAR2(64 BYTE)
, OURL VARCHAR2(128 BYTE)
, ODESC VARCHAR2(64 BYTE)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT S_OPERATE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 8192
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

COMMENT ON COLUMN S_OPERATE_11.OCODE IS '操作编号';
COMMENT ON COLUMN S_OPERATE_11.ONAME IS '操作名称';
COMMENT ON COLUMN S_OPERATE_11.TYPENAME IS '类型名称';
COMMENT ON COLUMN S_OPERATE_11.OURL IS '操作url';
COMMENT ON COLUMN S_OPERATE_11.ODESC IS '描述';
COMMENT ON COLUMN S_OPERATE_11.CREATETIME IS '创建时间';
COMMENT ON COLUMN S_OPERATE_11.LASTMODIFYTIME IS '修改时间';
COMMENT ON COLUMN S_OPERATE_11.CREATEUID IS '创建人';
COMMENT ON COLUMN S_OPERATE_11.LASTMODIFYUID IS '修改人ID';

----------------------------------------------------------------------权限组----------------------------------------------------------------------
CREATE TABLE S_OPERGROUP_11
(
  ID NUMBER NOT NULL
, GNAME VARCHAR2(64 BYTE)
, GDESC VARCHAR2(64 BYTE)
, INITUSE NUMBER(2, 0)
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT S_OPERGROUP_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

ALTER TABLE S_OPERGROUP_11
ADD CONSTRAINT SYS_C0054296 CHECK
(ID IS NOT NULL)
ENABLE;

COMMENT ON COLUMN S_OPERGROUP_11.GNAME IS '组名';
COMMENT ON COLUMN S_OPERGROUP_11.GDESC IS '描述';
COMMENT ON COLUMN S_OPERGROUP_11.INITUSE IS '是否默认';

----------------------------------------------------------------------权限组关联----------------------------------------------------------------------
CREATE TABLE S_OPERS_11
(
  GID NUMBER NOT NULL
, OID NUMBER NOT NULL
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

ALTER TABLE S_OPERS_11
ADD CONSTRAINT SYS_C0054297 CHECK
(GID IS NOT NULL)
ENABLE;

ALTER TABLE S_OPERS_11
ADD CONSTRAINT SYS_C0054298 CHECK
(OID IS NOT NULL)
ENABLE;

----------------------------------------------------------------------用户信息----------------------------------------------------------------------
CREATE TABLE I_USERINFO_11
(
  ID NUMBER NOT NULL
, USERNAME VARCHAR2(100 BYTE)
, PASSWORD VARCHAR2(300 BYTE)
, FULLNAME VARCHAR2(60 BYTE) DEFAULT NULL
, DEPARTID NUMBER
, DUTYID NUMBER
, CARDID VARCHAR2(100 BYTE)
, BIRTHDAY TIMESTAMP(6)
, HIREDATE TIMESTAMP(6)
, KEY VARCHAR2(200 BYTE)
, REMARK VARCHAR2(100 BYTE)
, SEX NUMBER(1, 0)
, POLICENUM VARCHAR2(100 BYTE)
, ULEVEL NUMBER(2, 0)
, ABLE NUMBER(1, 0)
, OGID NUMBER
, WORKPHONE VARCHAR2(50 BYTE)
, MOBILEPHONE VARCHAR2(50 BYTE)
, EMAIL VARCHAR2(100 BYTE)
, GZCODE CLOB
, QMCODE CLOB
, CREATEUID NUMBER
, CREATENAME VARCHAR2(32 BYTE)
, LASTMODIFYUID NUMBER
, CREATETIME TIMESTAMP(6)
, LASTMODIFYTIME TIMESTAMP(6)
, DELFLAG NUMBER
, CONSTRAINT USERINFO_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 8192
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
LOB (GZCODE) STORE AS SYS_LOB0000225634C00025$$
(
  ENABLE STORAGE IN ROW
  CHUNK 8192
  RETENTION
  NOCACHE
  LOGGING
  TABLESPACE "VILLAGE"
  STORAGE
  (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
)
LOB (QMCODE) STORE AS SYS_LOB0000225634C00026$$
(
  ENABLE STORAGE IN ROW
  CHUNK 8192
  RETENTION
  NOCACHE
  LOGGING
  TABLESPACE "VILLAGE"
  STORAGE
  (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
);

ALTER TABLE I_USERINFO_11
ADD CONSTRAINT SYS_C0050114 CHECK
(ID IS NOT NULL)
ENABLE;

COMMENT ON COLUMN I_USERINFO_11.ID IS '用户id';
COMMENT ON COLUMN I_USERINFO_11.USERNAME IS '登陆用户名称';
COMMENT ON COLUMN I_USERINFO_11.PASSWORD IS '用户密码（加密）';
COMMENT ON COLUMN I_USERINFO_11.FULLNAME IS '用户真实姓名';
COMMENT ON COLUMN I_USERINFO_11.DEPARTID IS '部门id';
COMMENT ON COLUMN I_USERINFO_11.DUTYID IS '职位id';
COMMENT ON COLUMN I_USERINFO_11.CARDID IS '用户身份证';
COMMENT ON COLUMN I_USERINFO_11.BIRTHDAY IS '生日';
COMMENT ON COLUMN I_USERINFO_11.HIREDATE IS '入职日期';
COMMENT ON COLUMN I_USERINFO_11.KEY IS '用户key';
COMMENT ON COLUMN I_USERINFO_11.REMARK IS '备注';
COMMENT ON COLUMN I_USERINFO_11.CREATETIME IS '创建日期';
COMMENT ON COLUMN I_USERINFO_11.LASTMODIFYTIME IS '更新日期';
COMMENT ON COLUMN I_USERINFO_11.CREATEUID IS '创建人id';
COMMENT ON COLUMN I_USERINFO_11.LASTMODIFYUID IS '更新人id';
COMMENT ON COLUMN I_USERINFO_11.SEX IS '性别 1男 0女';
COMMENT ON COLUMN I_USERINFO_11.POLICENUM IS '警号';
COMMENT ON COLUMN I_USERINFO_11.ULEVEL IS '用户级别';
COMMENT ON COLUMN I_USERINFO_11.DELFLAG IS '是否删除';
COMMENT ON COLUMN I_USERINFO_11.ABLE IS '1启用 0禁用';
COMMENT ON COLUMN I_USERINFO_11.OGID IS '权限组ID';
COMMENT ON COLUMN I_USERINFO_11.WORKPHONE IS '单位电话';
COMMENT ON COLUMN I_USERINFO_11.MOBILEPHONE IS '移动电话';
COMMENT ON COLUMN I_USERINFO_11.EMAIL IS '电子邮箱';
COMMENT ON COLUMN I_USERINFO_11.GZCODE IS '公章图片';
COMMENT ON COLUMN I_USERINFO_11.QMCODE IS '签名图片';
COMMENT ON COLUMN I_USERINFO_11.REGFLAG IS '注册标识';

CREATE UNIQUE INDEX USERINFO_CARDID_UINDEX ON I_USERINFO_11 (CARDID ASC)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 2
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

CREATE UNIQUE INDEX USERINFO_POLICENUM_UINDEX ON I_USERINFO_11 (POLICENUM ASC)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 2
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

CREATE UNIQUE INDEX USERINFO_USERNAME_UINDEX ON I_USERINFO_11 (USERNAME ASC)
LOGGING
TABLESPACE "VILLAGE"
PCTFREE 10
INITRANS 2
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-------------------------------------------------------motorvehicle-------------------------------


  CREATE TABLE "VILLAGE"."T_MOTORVEHICLE_19"
   (	"ID" VARCHAR2(64 BYTE),

  "MOTORVEHICLEID"	VARCHAR2(64),
  "PLATECLASS"	VARCHAR2(64),
  "PLATENO"	VARCHAR2(64),
  "VEHICLECLASS"	VARCHAR2(64),
  "VEHICLEBRAND"	VARCHAR2(256),
  "VEHICLEMODEL"	VARCHAR2(256),
  "VEHICLECOLOR"	VARCHAR2(256),
  "STORAGEURL1"	VARCHAR2(256),
  "STORAGEURL2"	VARCHAR2(256),
  "STORAGEURL3"	VARCHAR2(256),
  "VEHICLESTATUS"	VARCHAR2(256),
  "OWNERID"	VARCHAR2(64),
  "OWNERNAME"	VARCHAR2(256),
  "OWNERIDNUMBER"	VARCHAR2(256),
  "VILLAGEID"	VARCHAR2(64),

	"CREATETIME" TIMESTAMP (6),
	"LASTMODIFYTIME" TIMESTAMP (6),
	"CREATEUID" NUMBER,
	"LASTMODIFYUID" NUMBER,
	"CREATENAME" VARCHAR2(32 BYTE),
	"DELFLAG" NUMBER,
		 CONSTRAINT "T_MOTORVEHICLE_19" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE" ;


   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."ID" IS '唯一标识';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."MOTORVEHICLEID" IS '车辆编号';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."PLATECLASS" IS '号牌种类';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."PLATENO" IS '车牌号';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."VEHICLECLASS" IS '车辆类型';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."VEHICLEBRAND" IS '车辆品牌';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."VEHICLEMODEL" IS '车辆型号';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."VEHICLECOLOR" IS '车身颜色';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."STORAGEURL1" IS '近景照片';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."STORAGEURL2" IS '车牌照片';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."STORAGEURL3" IS '远景照片';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."VEHICLESTATUS" IS '车辆状态';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."OWNERID" IS '车主ID';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."OWNERNAME" IS '车主姓名';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."OWNERIDNUMBER" IS '车主证件号';
   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."VILLAGEID" IS '小区ID';


   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."CREATETIME" IS '创建时间';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."LASTMODIFYTIME" IS '修改时间';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."CREATEUID" IS '创建人ID';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."LASTMODIFYUID" IS '修改人ID';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."CREATENAME" IS '创建人名称';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."DELFLAG" IS '//删除标志';

--------------------------------------------------------------------------NonMotorVehicle---------------------------------------

  CREATE TABLE "VILLAGE"."T_NONMOTORVEHICLE_19"
   (	"ID" VARCHAR2(64 BYTE),
  "NONMOTORVEHICLEID"	VARCHAR2(64),
  "RFID"	VARCHAR2(64),
  "OWNERID"	VARCHAR2(256),
  "OWNERNAME"	VARCHAR2(256),
  "OWNERIDTYPE"	VARCHAR2(256),
  "OWNERIDNUMBER"	VARCHAR2(64),
  "PLATECLASS"	VARCHAR2(64),
  "PLATECOLOR"	VARCHAR2(64),
  "VEHICLEBRAND"	VARCHAR2(64),
  "VEHICLETYPE"	VARCHAR2(64),
  "VEHICLECOLOR"	VARCHAR2(64),
  "VILLAGEID"	VARCHAR2(64),
  "PHOTO"	VARCHAR2(64),
	"CREATETIME" TIMESTAMP (6),
	"LASTMODIFYTIME" TIMESTAMP (6),
	"CREATEUID" NUMBER,
	"LASTMODIFYUID" NUMBER,
	"CREATENAME" VARCHAR2(32 BYTE),
	"DELFLAG" NUMBER,
		 CONSTRAINT "T_NONMOTORVEHICLE_19" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE" ;


   COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."ID" IS '唯一标识';

    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."NONMOTORVEHICLEID" IS '车辆编号';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."RFID" IS 'RFID编号';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."OWNERID" IS '车主ID';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."OWNERNAME" IS '车主姓名';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."OWNERIDTYPE" IS '车主证件类型';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."OWNERIDNUMBER" IS '车主证件号';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."PLATECLASS" IS '号牌种类';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."PLATECOLOR" IS '车牌颜色';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."VEHICLEBRAND" IS '车辆品牌';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."VEHICLETYPE" IS '车辆款型';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."VEHICLECOLOR" IS '车身颜色';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."VILLAGEID" IS '小区编号';
    COMMENT ON COLUMN "VILLAGE"."T_NONMOTORVEHICLE_19"."PHOTO" IS '照片';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."CREATETIME" IS '创建时间';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."LASTMODIFYTIME" IS '修改时间';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."CREATEUID" IS '创建人ID';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."LASTMODIFYUID" IS '修改人ID';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."CREATENAME" IS '创建人名称';

   COMMENT ON COLUMN "VILLAGE"."T_MOTORVEHICLE_19"."DELFLAG" IS '//删除标志';


---------------------------------------------------ElectronicFenceLog----------------------------------------------------

CREATE TABLE "VILLAGE"."T_ELECTRONICFENCELOG_19"
   (	"ID" VARCHAR2(64 BYTE),

    "VILLAGEID"	VARCHAR2(64),
    "VILLAGENAME"	VARCHAR2(50),
    "LOC"	VARCHAR2(50),
    "TYPE"	VARCHAR2(50),
    "ALERT_DATE"	TIMESTAMP (6),
    "DEVICEID"	VARCHAR2(256),
    "DISPLAY_FLAG"	VARCHAR2(2),
    "LONGITUDE"	VARCHAR2(20),
    "LATITUDE"	VARCHAR2(20),
	  "CREATEDATE" TIMESTAMP (6),
    "ALERTCOUNT"	VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE" ;


   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."ID" IS '唯一标识';


   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."VILLAGEID" IS '小区编号';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."VILLAGENAME" IS '小区姓名';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."LOC" IS '栅栏位置';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."TYPE" IS '报警类型';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."ALERT_DATE" IS '报警时间';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."DEVICEID" IS '设备ID';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."DISPLAY_FLAG" IS '是否弹出';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."LONGITUDE" IS '经度';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."LATITUDE" IS '纬度';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."CREATEDATE" IS '创建时间';
   COMMENT ON COLUMN "VILLAGE"."T_ELECTRONICFENCELOG_19"."ALERTCOUNT" IS '报警次数';

--------------------------------------------------------------------T_HOUSEOWNER_19--------------------------------------

CREATE TABLE "VILLAGE"."T_HOUSEOWNER_19"
   (	"ID" VARCHAR2(64 BYTE),
  "OWNERID"  VARCHAR2(64 BYTE),
  "HOUSEID"  VARCHAR2(64 BYTE),
    "UNITID"  VARCHAR2(64 BYTE),

    "BUILDINGID" VARCHAR2(64 BYTE),
    "VILLAGEID" VARCHAR2(64 BYTE),


	"CREATETIME" TIMESTAMP (6),
	"LASTMODIFYTIME" TIMESTAMP (6),
	"CREATEUID" NUMBER,
	"LASTMODIFYUID" NUMBER,
	"CREATENAME" VARCHAR2(32 BYTE),
	"DELFLAG" NUMBER,
		 CONSTRAINT "T_HOUSEOWNER_19" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE" ;


   COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."ID" IS '唯一标识';
  COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."OWNERID" IS '业主编号（身份证）';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."HOUSEID" IS '房屋编号';

    COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."UNITID" IS '单元编号';
   COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."BUILDINGID" IS '楼栋编号';
    COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."VILLAGEID" IS '小区编号';



   COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."CREATETIME" IS '创建时间';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."LASTMODIFYTIME" IS '修改时间';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."CREATEUID" IS '创建人ID';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."LASTMODIFYUID" IS '修改人ID';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."CREATENAME" IS '创建人名称';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSEOWNER_19"."DELFLAG" IS '//删除标志';


   ---------------------------------------------------业主信息------------------------------------------

   CREATE TABLE "VILLAGE"."T_OWNER_19"
   (	"ID" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"IDTYPE" NUMBER,
	"IDNUMBER" VARCHAR2(256 BYTE),
	"NAME" VARCHAR2(256 BYTE),
	"SEX" NUMBER,
	"BIRTHDAY" VARCHAR2(256 BYTE),
	"NATION" NUMBER,
	"POLITICSSTATUS" VARCHAR2(256 BYTE),
	"EDUCATIONSTATUS" VARCHAR2(256 BYTE),
	"PHONE" VARCHAR2(256 BYTE),
	"JOB" VARCHAR2(256 BYTE),
	"WORKPLACE" VARCHAR2(256 BYTE),
	"PHOTO" VARCHAR2(256 BYTE),
	"IDPHOTO" VARCHAR2(256 BYTE),
	"IDADDR" VARCHAR2(256 BYTE),
	"VILLAGEID" VARCHAR2(256 BYTE),
	"IDENTIFY_TYPE" NUMBER,
	"IDENTIFY_COUNTRY" NUMBER,
	"CREATETIME" TIMESTAMP (6),
	"LASTMODIFYTIME" TIMESTAMP (6),
	"CREATEUID" NUMBER,
	"LASTMODIFYUID" NUMBER,
	"CREATENAME" VARCHAR2(32 BYTE),
	"DELFLAG" NUMBER,
	 CONSTRAINT "T_OWNER_19_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE" ;


   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."ID" IS '唯一标识';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."IDTYPE" IS '证件类型（需要码表）';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."IDNUMBER" IS '证件号码';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."NAME" IS '姓名';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."SEX" IS '性别（需要码表）';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."BIRTHDAY" IS '出生日期';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."NATION" IS '民族（需要码表）';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."POLITICSSTATUS" IS '政治面貌';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."EDUCATIONSTATUS" IS '文化程度';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."PHONE" IS '联系电话';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."JOB" IS '从事职业';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."WORKPLACE" IS '服务处所';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."PHOTO" IS '照片';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."IDPHOTO" IS '证件照片';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."IDADDR" IS '户籍地址';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."VILLAGEID" IS '小区编号';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."IDENTIFY_TYPE" IS '身份类型（业主、家人、租客、临时客人）1:业主，2：家属，3：租户，4：访客，9：其他';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."IDENTIFY_COUNTRY" IS '所属国家（需要国际码表）';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."CREATETIME" IS '创建时间';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."LASTMODIFYTIME" IS '修改时间';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."CREATEUID" IS '创建人ID';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."LASTMODIFYUID" IS '修改人ID';


   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."CREATENAME" IS '创建人名称';

   COMMENT ON COLUMN "VILLAGE"."T_OWNER_19"."DELFLAG" IS '//删除标志';


----------------------------------------------房屋租赁管理------------------------------------------------------------------------

CREATE TABLE "VILLAGE"."T_HOUSELOG_19"
   (	"ID" VARCHAR2(64 BYTE) NOT NULL ENABLE,
    "IDNUMBER" VARCHAR2(256 BYTE),
    "HOUSENO" VARCHAR2(64 BYTE),
  "STARTTIME" TIMESTAMP (6),
  "ENDTIME" TIMESTAMP (6),
	"CREATETIME" TIMESTAMP (6),
	"LASTMODIFYTIME" TIMESTAMP (6),
	"CREATEUID" NUMBER,
	"LASTMODIFYUID" NUMBER,
	"CREATENAME" VARCHAR2(32 BYTE),
	"DELFLAG" NUMBER,
	 CONSTRAINT "T_HOUSELOG_19" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE" ;


    COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."ID" IS '唯一标识';
    COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."IDNUMBER" IS '证件号码';
    COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."HOUSENO" IS '房屋编号';
    COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."STARTTIME" IS '开始时间';
    COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."ENDTIME" IS '结束时间';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."CREATETIME" IS '创建时间';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."LASTMODIFYTIME" IS '修改时间';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."CREATEUID" IS '创建人ID';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."LASTMODIFYUID" IS '修改人ID';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."CREATENAME" IS '创建人名称';

   COMMENT ON COLUMN "VILLAGE"."T_HOUSELOG_19"."DELFLAG" IS '//删除标志';

----------------------------------------------------------------------车位租赁管理-------------------------------------------
CREATE TABLE "VILLAGE"."T_PRAKINGLOG_19"
   (	"ID" VARCHAR2(64 BYTE) NOT NULL ENABLE,
    "PARKINGNO" VARCHAR2(64 BYTE),
    "PLATENO" VARCHAR2(64 BYTE),
  "STARTTIME" TIMESTAMP (6),
  "ENDTIME" TIMESTAMP (6),
	"CREATETIME" TIMESTAMP (6),
	"LASTMODIFYTIME" TIMESTAMP (6),
	"CREATEUID" NUMBER,
	"LASTMODIFYUID" NUMBER,
	"CREATENAME" VARCHAR2(32 BYTE),
	"DELFLAG" NUMBER,
	 CONSTRAINT "T_PRAKINGLOG_19" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE" ;


    COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."ID" IS '唯一标识';
    COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."PARKINGNO" IS '车位编号';
    COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."PLATENO" IS '车牌号';
    COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."STARTTIME" IS '开始时间';
    COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."ENDTIME" IS '结束时间';

   COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."CREATETIME" IS '创建时间';

   COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."LASTMODIFYTIME" IS '修改时间';

   COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."CREATEUID" IS '创建人ID';

   COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."LASTMODIFYUID" IS '修改人ID';

   COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."CREATENAME" IS '创建人名称';

   COMMENT ON COLUMN "VILLAGE"."T_PRAKINGLOG_19"."DELFLAG" IS '//删除标志';

--------------------------------------------------------------------小区基础信息表-----------------

  CREATE TABLE "VILLAGE"."T_VILLAGE_19"
   (	"ID" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"VILLAGEID" VARCHAR2(64 BYTE),
	"VILLAGETYPE" VARCHAR2(64 BYTE),
	"VILLAGENAME" VARCHAR2(256 BYTE),
	"VILLAGEIMG" VARCHAR2(256 BYTE),
	"VILLAGEREGION" VARCHAR2(256 BYTE),
	"SUBBUREAU" VARCHAR2(32 BYTE),
	"DISTRICT" VARCHAR2(32 BYTE),
  "STANDARDADDR" VARCHAR2(256 BYTE),
	"STANDARDADDRCODE" VARCHAR2(256 BYTE),
	"BUILDINGNUM" VARCHAR2(256 BYTE),
	"HOUSENUM" VARCHAR2(256 BYTE),
	"RESIDENTNUM" VARCHAR2(256 BYTE),
	"PERMANENTRESIDENTNUM" VARCHAR2(256 BYTE),
	"TEMPORARYRESIDENTNUM" VARCHAR2(256 BYTE),
	"GUESTRESIDENTNUM" VARCHAR2(256 BYTE),
	"PARKINGSPACENUM" VARCHAR2(256 BYTE),
	"MOTORVEHICLENUM" VARCHAR2(256 BYTE),
	"NONMOTORVEHICLENUM" VARCHAR2(256 BYTE),
	"SHEDNUM" VARCHAR2(256 BYTE),
	"UNITNUM" VARCHAR2(256 BYTE),
	"FOREIGNNUM" VARCHAR2(256 BYTE),
	"CHARGNUM" VARCHAR2(256 BYTE),
	"PROBENNUM" VARCHAR2(256 BYTE),
	"LOGO1" VARCHAR2(256 BYTE),
	"LOGO2" VARCHAR2(256 BYTE),
	"LOGO3" VARCHAR2(256 BYTE),
	"LOGO4" VARCHAR2(256 BYTE),
	"CREATETIME" TIMESTAMP (6),
	"LASTMODIFYTIME" TIMESTAMP (6),
	"CREATEUID" NUMBER,
	"LASTMODIFYUID" NUMBER,
	"CREATENAME" VARCHAR2(32 BYTE),
	"DELFLAG" NUMBER,
	 CONSTRAINT "T_VILLAGE_19_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE" ;


   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."ID" IS '唯一标识';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."VILLAGEID" IS '小区编号';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."VILLAGETYPE" IS '小区类型';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."VILLAGENAME" IS '小区名称';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."VILLAGEIMG" IS '照片（URL';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."VILLAGEREGION" IS '小区区域(有经纬度描述顶点的多边形)';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."SUBBUREAU" IS '所属分局(需要字典表这里存的应该是分局标识)';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."DISTRICT" IS '所属行政区划(需要行政区域字典表存的应该是标识)';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."STANDARDADDR" IS '标准地址';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."STANDARDADDRCODE" IS '标准地址编码';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."BUILDINGNUM" IS '居民楼数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."HOUSENUM" IS '房屋数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."RESIDENTNUM" IS '总人数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."PERMANENTRESIDENTNUM" IS '常住人口数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."TEMPORARYRESIDENTNUM" IS '暂住人口数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."GUESTRESIDENTNUM" IS '寄住人口数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."PARKINGSPACENUM" IS '停车位数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."MOTORVEHICLENUM" IS '机动车数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."NONMOTORVEHICLENUM" IS '非机动车数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."SHEDNUM" IS '车棚数';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."UNITNUM" IS '单元数量';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."FOREIGNNUM" IS '境外人口数量';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."CHARGNUM" IS '充电庄数量';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."PROBENNUM" IS '探头数量';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."LOGO1" IS 'logo1';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."LOGO2" IS 'logo2';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."LOGO3" IS 'logo3';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."LOGO4" IS 'logo4';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."CREATETIME" IS '创建时间';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."LASTMODIFYTIME" IS '修改时间';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."CREATEUID" IS '创建人ID';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."LASTMODIFYUID" IS '修改人ID';

   COMMENT ON COLUMN "VILLAGE"."T_VILLAGE_19"."CREATENAME" IS '创建人名称';

   -----------------------------------------------------地址编码字典表---------------------------------------------

   CREATE TABLE "VILLAGE"."P_CITYSDATA_19"
   (	"ID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
	"PROVINCEID" VARCHAR2(32 BYTE),
	"PROVINCENAME" VARCHAR2(200 BYTE),
	"CITYID" VARCHAR2(32 BYTE),
	"CITYNAME" VARCHAR2(200 BYTE),
	"AREAID" VARCHAR2(32 BYTE),
	"AREANAME" VARCHAR2(200 BYTE),
	"CONTRYID" VARCHAR2(32 BYTE),
	"CONTRYNAME" VARCHAR2(200 BYTE),
	"LON" VARCHAR2(100 BYTE),
	"LAT" VARCHAR2(100 BYTE),
	"PHONECODE" VARCHAR2(100 BYTE),
	"CREATETIME" TIMESTAMP (6),
	"LASTMODIFYTIME" TIMESTAMP (6),
	"CREATEUID" NUMBER,
	"LASTMODIFYUID" NUMBER,
	"CREATENAME" VARCHAR2(32 BYTE),
	"DELFLAG" NUMBER,
	 CONSTRAINT "P_CITYSDATA_19_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VILLAGE" ;


   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."ID" IS ' 唯一值';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."PROVINCEID" IS '省ID';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."PROVINCENAME" IS '省名称';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."CITYID" IS '市ID';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."CITYNAME" IS '市名称';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."AREAID" IS '区/县/城镇ID';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."AREANAME" IS '区/县/城镇名称';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."CONTRYID" IS '乡镇街道ID';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."CONTRYNAME" IS '乡镇街道';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."LON" IS '经度';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."LAT" IS '纬度';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."PHONECODE" IS '电话区号';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."CREATETIME" IS '创建时间';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."LASTMODIFYTIME" IS '修改时间';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."CREATEUID" IS '创建人id';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."LASTMODIFYUID" IS '更新人id';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."CREATENAME" IS '创建人名称';

   COMMENT ON COLUMN "VILLAGE"."P_CITYSDATA_19"."DELFLAG" IS '删除标记';





